# print messages to rosconsole as well
log_msgs: false

# add all limits to diagnostics
debug: false

# update rate for diagnostics
rate: 0.5

# can go that far outside limits without an error
limit_tolerance: 0.05
# getting that close to the limits (fraction of full range) will trigger a warning
warn_close_to_limit_fraction: 0.05

# per-joint overrides
joints:
  panda_finger_joint1:
    warn_limit_margin: 0.0
  panda_joint6:
    limit_tolerance: 0.1
